[build]
  command = "npm run build"
  publish = "build"

[context.production.environment]
  NODE_ENV = "production"
  REACT_APP_API_URL = "https://naijahomes.onrender.com"

[[redirects]]
  from = "/api/*"
  to = "https://naijahomes.onrender.com/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
