[build]
  command = "npm run build"
  publish = "build"

[dev]
  command = "npm start"
  port = 3000

[context.production.environment]
  NODE_ENV = "production"
  REACT_APP_API_URL = "https://naijahomes.onrender.com" # Your Render backend URL

[[redirects]]
  from = "/api/*"
  to = "https://naijahomes.onrender.com/:splat"
  status = 200
  force = true
